#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
FROM php:7.0-cli
RUN apt-get update
RUN apt-get install -y wget \
  curl \
  git \
#  build-base \
  libmemcached-dev \
  libmcrypt-dev \
  libxml2-dev \
  zlib1g-dev \
  autoconf \
#  cyrus-sasl-dev \
#  libgsasl-dev \
  libpng-dev \
  supervisor

RUN docker-php-ext-install mysqli mbstring pdo_mysql tokenizer xml zip xml gd

RUN pecl channel-update pecl.php.net && pecl install memcached mcrypt-1.0.1 && docker-php-ext-enable memcached
# Install PostgreSQL drivers:
ARG INSTALL_PGSQL=false
RUN if [ ${INSTALL_PGSQL} = true ]; then \
    apt-get install -y postgresql-dev \
        && docker-php-ext-install pdo_pgsql \
;fi

RUN mkdir -p /var/www

#
#--------------------------------------------------------------------------
# Optional Supervisord Configuration
#--------------------------------------------------------------------------
#
# Modify the ./supervisor.conf file to match your App's requirements.
# Make sure you rebuild your container with every change.
#

COPY supervisord.conf /etc/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

#
#--------------------------------------------------------------------------
# Optional Software's Installation
#--------------------------------------------------------------------------
#
# If you need to modify this image, feel free to do it right here.
#
    # -- Your awesome modifications go here -- #
    # Install Redis

ARG INSTALL_PHPREDIS=true
ENV INSTALL_PHPREDIS ${INSTALL_PHPREDIS}
RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
    # Install Php Redis extension
    pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis \
;fi

# RUN apt-get install -y libpng-dev && docker-php-ext-install zip xml gd

# COPY ./application/ /var/www/

#
#--------------------------------------------------------------------------
# Check PHP version
#--------------------------------------------------------------------------
#
RUN php -v | head -n 1 | grep -q "PHP 7.0."
#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#
WORKDIR /etc/supervisor/conf.d/
